/********************************************************************************
** Form generated from reading UI file 'stockman.ui'
**
** Created by: Qt User Interface Compiler version 6.5.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_STOCKMAN_H
#define UI_STOCKMAN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Stockman
{
public:
    QWidget *centralwidget;
    QLabel *label_menu_fundo;
    QLabel *logo_menu;
    QLabel *label_clientes_menu;
    QLabel *label_produtos_menu;
    QLabel *label_fornecedores_menu;
    QLabel *icon_clientes;
    QLabel *icon_produtos;
    QLabel *icon_fornecedores;
    QTabWidget *menu;
    QWidget *home;
    QLabel *hero;
    QWidget *clientes;
    QLabel *h1_clientes;
    QTabWidget *tabWidget;
    QWidget *cadastro_cliente;
    QLabel *p_nome;
    QLineEdit *cliente_nome;
    QLabel *p_nome_2;
    QLineEdit *cliente_email;
    QLabel *p_nome_3;
    QLineEdit *cliente_endereco;
    QLabel *p_nome_4;
    QLineEdit *cliente_complemento;
    QLabel *p_nome_5;
    QLineEdit *cliente_cpf;
    QLabel *p_nome_6;
    QLineEdit *cliente_telefone;
    QPushButton *cadastrar_cliente;
    QWidget *pesquisa_cliente;
    QLabel *p_nome_7;
    QLineEdit *campo_cliente_pesquisa;
    QPushButton *pesquisa_cliente_2;
    QLabel *p_nome_21;
    QLabel *p_nome_22;
    QLabel *p_nome_23;
    QLabel *p_nome_24;
    QLabel *p_nome_25;
    QLabel *p_nome_26;
    QLabel *p_nome_27;
    QLabel *imprimir_nome_cliente;
    QLabel *imprimir_email_cliente;
    QLabel *imprimir_endereco_cliente;
    QLabel *imprimir_complemento_cliente;
    QLabel *imprimir_cpf_cliente;
    QLabel *imprimir_telefone_cliente;
    QPushButton *pushButton;
    QWidget *produtos;
    QLabel *h1_produtos;
    QTabWidget *tabWidget_2;
    QWidget *cadastro_produto;
    QLabel *p_nome_8;
    QLabel *p_nome_9;
    QLabel *p_nome_10;
    QLabel *p_nome_11;
    QLabel *p_nome_12;
    QLineEdit *nome_produto;
    QLineEdit *fornecedor_produto;
    QLineEdit *codigo_produto;
    QLineEdit *qtd_produto;
    QLineEdit *valor_produto;
    QPushButton *cadastrar_produto;
    QWidget *pesquisa_produtos;
    QLabel *p_nome_13;
    QLineEdit *campo_produto_pesquisa;
    QPushButton *pesquisa_produto;
    QLabel *p_nome_28;
    QLabel *p_nome_29;
    QLabel *p_nome_30;
    QLabel *p_nome_31;
    QLabel *p_nome_32;
    QLabel *p_nome_33;
    QPushButton *nova_consulta_produtos;
    QLabel *imprimir_nome_produto;
    QLabel *imprimir_fornecedor_produto;
    QLabel *imprimir_codigo_produto;
    QLabel *imprimir_qtd_produto;
    QLabel *imprimir_valor_produto;
    QWidget *fornecedores;
    QLabel *h1_fornecedores;
    QTabWidget *tabWidget_3;
    QWidget *cadastro_fornecedores;
    QLabel *p_nome_14;
    QLineEdit *nome_fornecedor;
    QLabel *p_nome_15;
    QLineEdit *email_fornecedor;
    QLabel *p_nome_16;
    QLineEdit *endereco_fornecedor;
    QLabel *p_nome_17;
    QLineEdit *complemento_fornecedor;
    QLabel *p_nome_18;
    QLineEdit *cnpj_fornecedor;
    QLabel *p_nome_19;
    QLineEdit *telefone_fornecedor;
    QPushButton *cadastrar_fornecedor;
    QWidget *pesquisa_fornecedores;
    QLabel *p_nome_20;
    QLineEdit *campo_pesquisa_fornecedor;
    QPushButton *pesquisa_fornecedor;
    QLabel *p_nome_34;
    QLabel *p_nome_35;
    QLabel *p_nome_36;
    QLabel *p_nome_37;
    QLabel *p_nome_38;
    QLabel *p_nome_39;
    QLabel *p_nome_40;
    QLabel *imprimir_nome_fornecedor;
    QLabel *imprimir_email_fornecedor;
    QLabel *imprimir_endereco_fornecedor;
    QLabel *imprimir_complemento_fornecedor;
    QLabel *imprimir_cnpj_fornecedor;
    QLabel *imprimir_telefone_fornecedor;
    QPushButton *nova_consulta_fornecedor;

    void setupUi(QMainWindow *Stockman)
    {
        if (Stockman->objectName().isEmpty())
            Stockman->setObjectName("Stockman");
        Stockman->resize(1920, 1080);
        centralwidget = new QWidget(Stockman);
        centralwidget->setObjectName("centralwidget");
        label_menu_fundo = new QLabel(centralwidget);
        label_menu_fundo->setObjectName("label_menu_fundo");
        label_menu_fundo->setGeometry(QRect(0, 0, 450, 1080));
        label_menu_fundo->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);"));
        logo_menu = new QLabel(centralwidget);
        logo_menu->setObjectName("logo_menu");
        logo_menu->setGeometry(QRect(80, 60, 241, 201));
        logo_menu->setPixmap(QPixmap(QString::fromUtf8("../build-Stockman-Desktop_Qt_6_5_2_GCC_64bit-Debug/img/logo.png")));
        label_clientes_menu = new QLabel(centralwidget);
        label_clientes_menu->setObjectName("label_clientes_menu");
        label_clientes_menu->setGeometry(QRect(170, 330, 121, 41));
        QFont font;
        font.setFamilies({QString::fromUtf8("Comfortaa")});
        font.setPointSize(15);
        label_clientes_menu->setFont(font);
        label_clientes_menu->setStyleSheet(QString::fromUtf8("color:white;"));
        label_produtos_menu = new QLabel(centralwidget);
        label_produtos_menu->setObjectName("label_produtos_menu");
        label_produtos_menu->setGeometry(QRect(170, 410, 121, 41));
        label_produtos_menu->setFont(font);
        label_produtos_menu->setStyleSheet(QString::fromUtf8("color:white;"));
        label_fornecedores_menu = new QLabel(centralwidget);
        label_fornecedores_menu->setObjectName("label_fornecedores_menu");
        label_fornecedores_menu->setGeometry(QRect(170, 490, 191, 41));
        label_fornecedores_menu->setFont(font);
        label_fornecedores_menu->setStyleSheet(QString::fromUtf8("color:white;"));
        icon_clientes = new QLabel(centralwidget);
        icon_clientes->setObjectName("icon_clientes");
        icon_clientes->setGeometry(QRect(100, 320, 41, 41));
        icon_clientes->setPixmap(QPixmap(QString::fromUtf8("../build-Stockman-Desktop_Qt_6_5_2_GCC_64bit-Debug/img/icon _cliente.svg")));
        icon_produtos = new QLabel(centralwidget);
        icon_produtos->setObjectName("icon_produtos");
        icon_produtos->setGeometry(QRect(100, 400, 41, 51));
        icon_produtos->setPixmap(QPixmap(QString::fromUtf8("../build-Stockman-Desktop_Qt_6_5_2_GCC_64bit-Debug/img/icon _produto.svg")));
        icon_fornecedores = new QLabel(centralwidget);
        icon_fornecedores->setObjectName("icon_fornecedores");
        icon_fornecedores->setGeometry(QRect(110, 480, 31, 51));
        icon_fornecedores->setPixmap(QPixmap(QString::fromUtf8("../build-Stockman-Desktop_Qt_6_5_2_GCC_64bit-Debug/img/icon_forne.svg")));
        menu = new QTabWidget(centralwidget);
        menu->setObjectName("menu");
        menu->setGeometry(QRect(450, 0, 1470, 1080));
        home = new QWidget();
        home->setObjectName("home");
        hero = new QLabel(home);
        hero->setObjectName("hero");
        hero->setGeometry(QRect(0, 0, 1470, 1080));
        hero->setPixmap(QPixmap(QString::fromUtf8("../build-Stockman-Desktop_Qt_6_5_2_GCC_64bit-Debug/img/hero.png")));
        menu->addTab(home, QString());
        clientes = new QWidget();
        clientes->setObjectName("clientes");
        h1_clientes = new QLabel(clientes);
        h1_clientes->setObjectName("h1_clientes");
        h1_clientes->setGeometry(QRect(30, 30, 191, 71));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Comfortaa")});
        font1.setPointSize(25);
        font1.setBold(true);
        h1_clientes->setFont(font1);
        tabWidget = new QTabWidget(clientes);
        tabWidget->setObjectName("tabWidget");
        tabWidget->setGeometry(QRect(40, 110, 1470, 1080));
        cadastro_cliente = new QWidget();
        cadastro_cliente->setObjectName("cadastro_cliente");
        p_nome = new QLabel(cadastro_cliente);
        p_nome->setObjectName("p_nome");
        p_nome->setGeometry(QRect(40, 50, 81, 41));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Droid Sans")});
        font2.setPointSize(15);
        p_nome->setFont(font2);
        cliente_nome = new QLineEdit(cadastro_cliente);
        cliente_nome->setObjectName("cliente_nome");
        cliente_nome->setGeometry(QRect(40, 90, 750, 55));
        p_nome_2 = new QLabel(cadastro_cliente);
        p_nome_2->setObjectName("p_nome_2");
        p_nome_2->setGeometry(QRect(40, 170, 81, 41));
        p_nome_2->setFont(font2);
        cliente_email = new QLineEdit(cadastro_cliente);
        cliente_email->setObjectName("cliente_email");
        cliente_email->setGeometry(QRect(40, 210, 750, 55));
        p_nome_3 = new QLabel(cadastro_cliente);
        p_nome_3->setObjectName("p_nome_3");
        p_nome_3->setGeometry(QRect(40, 280, 131, 41));
        p_nome_3->setFont(font2);
        cliente_endereco = new QLineEdit(cadastro_cliente);
        cliente_endereco->setObjectName("cliente_endereco");
        cliente_endereco->setGeometry(QRect(40, 320, 750, 55));
        p_nome_4 = new QLabel(cadastro_cliente);
        p_nome_4->setObjectName("p_nome_4");
        p_nome_4->setGeometry(QRect(40, 390, 181, 41));
        p_nome_4->setFont(font2);
        cliente_complemento = new QLineEdit(cadastro_cliente);
        cliente_complemento->setObjectName("cliente_complemento");
        cliente_complemento->setGeometry(QRect(40, 430, 750, 55));
        p_nome_5 = new QLabel(cadastro_cliente);
        p_nome_5->setObjectName("p_nome_5");
        p_nome_5->setGeometry(QRect(40, 500, 181, 41));
        p_nome_5->setFont(font2);
        cliente_cpf = new QLineEdit(cadastro_cliente);
        cliente_cpf->setObjectName("cliente_cpf");
        cliente_cpf->setGeometry(QRect(40, 540, 350, 55));
        p_nome_6 = new QLabel(cadastro_cliente);
        p_nome_6->setObjectName("p_nome_6");
        p_nome_6->setGeometry(QRect(430, 500, 181, 41));
        p_nome_6->setFont(font2);
        cliente_telefone = new QLineEdit(cadastro_cliente);
        cliente_telefone->setObjectName("cliente_telefone");
        cliente_telefone->setGeometry(QRect(430, 540, 350, 55));
        cadastrar_cliente = new QPushButton(cadastro_cliente);
        cadastrar_cliente->setObjectName("cadastrar_cliente");
        cadastrar_cliente->setGeometry(QRect(40, 650, 350, 55));
        cadastrar_cliente->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);\n"
"color: white;"));
        tabWidget->addTab(cadastro_cliente, QString());
        pesquisa_cliente = new QWidget();
        pesquisa_cliente->setObjectName("pesquisa_cliente");
        p_nome_7 = new QLabel(pesquisa_cliente);
        p_nome_7->setObjectName("p_nome_7");
        p_nome_7->setGeometry(QRect(60, 50, 431, 41));
        p_nome_7->setFont(font2);
        campo_cliente_pesquisa = new QLineEdit(pesquisa_cliente);
        campo_cliente_pesquisa->setObjectName("campo_cliente_pesquisa");
        campo_cliente_pesquisa->setGeometry(QRect(490, 40, 650, 55));
        pesquisa_cliente_2 = new QPushButton(pesquisa_cliente);
        pesquisa_cliente_2->setObjectName("pesquisa_cliente_2");
        pesquisa_cliente_2->setGeometry(QRect(1160, 40, 150, 55));
        pesquisa_cliente_2->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);\n"
"color: rgb(255, 255, 255);"));
        p_nome_21 = new QLabel(pesquisa_cliente);
        p_nome_21->setObjectName("p_nome_21");
        p_nome_21->setGeometry(QRect(60, 150, 111, 41));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("DejaVu Sans")});
        font3.setPointSize(15);
        font3.setBold(true);
        p_nome_21->setFont(font3);
        p_nome_22 = new QLabel(pesquisa_cliente);
        p_nome_22->setObjectName("p_nome_22");
        p_nome_22->setGeometry(QRect(60, 210, 91, 41));
        p_nome_22->setFont(font2);
        p_nome_23 = new QLabel(pesquisa_cliente);
        p_nome_23->setObjectName("p_nome_23");
        p_nome_23->setGeometry(QRect(60, 260, 91, 41));
        p_nome_23->setFont(font2);
        p_nome_24 = new QLabel(pesquisa_cliente);
        p_nome_24->setObjectName("p_nome_24");
        p_nome_24->setGeometry(QRect(60, 310, 131, 41));
        p_nome_24->setFont(font2);
        p_nome_25 = new QLabel(pesquisa_cliente);
        p_nome_25->setObjectName("p_nome_25");
        p_nome_25->setGeometry(QRect(60, 360, 181, 41));
        p_nome_25->setFont(font2);
        p_nome_26 = new QLabel(pesquisa_cliente);
        p_nome_26->setObjectName("p_nome_26");
        p_nome_26->setGeometry(QRect(60, 410, 61, 41));
        p_nome_26->setFont(font2);
        p_nome_27 = new QLabel(pesquisa_cliente);
        p_nome_27->setObjectName("p_nome_27");
        p_nome_27->setGeometry(QRect(60, 460, 111, 41));
        p_nome_27->setFont(font2);
        imprimir_nome_cliente = new QLabel(pesquisa_cliente);
        imprimir_nome_cliente->setObjectName("imprimir_nome_cliente");
        imprimir_nome_cliente->setGeometry(QRect(150, 210, 800, 30));
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Comfortaa")});
        font4.setPointSize(13);
        imprimir_nome_cliente->setFont(font4);
        imprimir_email_cliente = new QLabel(pesquisa_cliente);
        imprimir_email_cliente->setObjectName("imprimir_email_cliente");
        imprimir_email_cliente->setGeometry(QRect(150, 270, 800, 30));
        imprimir_email_cliente->setFont(font4);
        imprimir_endereco_cliente = new QLabel(pesquisa_cliente);
        imprimir_endereco_cliente->setObjectName("imprimir_endereco_cliente");
        imprimir_endereco_cliente->setGeometry(QRect(190, 320, 800, 30));
        imprimir_endereco_cliente->setFont(font4);
        imprimir_complemento_cliente = new QLabel(pesquisa_cliente);
        imprimir_complemento_cliente->setObjectName("imprimir_complemento_cliente");
        imprimir_complemento_cliente->setGeometry(QRect(250, 370, 800, 30));
        imprimir_complemento_cliente->setFont(font4);
        imprimir_cpf_cliente = new QLabel(pesquisa_cliente);
        imprimir_cpf_cliente->setObjectName("imprimir_cpf_cliente");
        imprimir_cpf_cliente->setGeometry(QRect(130, 420, 800, 30));
        imprimir_cpf_cliente->setFont(font4);
        imprimir_telefone_cliente = new QLabel(pesquisa_cliente);
        imprimir_telefone_cliente->setObjectName("imprimir_telefone_cliente");
        imprimir_telefone_cliente->setGeometry(QRect(180, 470, 800, 30));
        imprimir_telefone_cliente->setFont(font4);
        pushButton = new QPushButton(pesquisa_cliente);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(60, 750, 251, 55));
        pushButton->setStyleSheet(QString::fromUtf8("background-color: rgb(224, 27, 36);\n"
"color: rgb(255, 255, 255);"));
        tabWidget->addTab(pesquisa_cliente, QString());
        menu->addTab(clientes, QString());
        produtos = new QWidget();
        produtos->setObjectName("produtos");
        h1_produtos = new QLabel(produtos);
        h1_produtos->setObjectName("h1_produtos");
        h1_produtos->setGeometry(QRect(30, 30, 271, 61));
        h1_produtos->setFont(font1);
        tabWidget_2 = new QTabWidget(produtos);
        tabWidget_2->setObjectName("tabWidget_2");
        tabWidget_2->setGeometry(QRect(30, 100, 1470, 1080));
        cadastro_produto = new QWidget();
        cadastro_produto->setObjectName("cadastro_produto");
        p_nome_8 = new QLabel(cadastro_produto);
        p_nome_8->setObjectName("p_nome_8");
        p_nome_8->setGeometry(QRect(80, 40, 91, 41));
        p_nome_8->setFont(font2);
        p_nome_9 = new QLabel(cadastro_produto);
        p_nome_9->setObjectName("p_nome_9");
        p_nome_9->setGeometry(QRect(80, 150, 161, 41));
        p_nome_9->setFont(font2);
        p_nome_10 = new QLabel(cadastro_produto);
        p_nome_10->setObjectName("p_nome_10");
        p_nome_10->setGeometry(QRect(80, 260, 101, 41));
        p_nome_10->setFont(font2);
        p_nome_11 = new QLabel(cadastro_produto);
        p_nome_11->setObjectName("p_nome_11");
        p_nome_11->setGeometry(QRect(80, 360, 211, 41));
        p_nome_11->setFont(font2);
        p_nome_12 = new QLabel(cadastro_produto);
        p_nome_12->setObjectName("p_nome_12");
        p_nome_12->setGeometry(QRect(460, 360, 101, 41));
        p_nome_12->setFont(font2);
        nome_produto = new QLineEdit(cadastro_produto);
        nome_produto->setObjectName("nome_produto");
        nome_produto->setGeometry(QRect(80, 80, 650, 55));
        fornecedor_produto = new QLineEdit(cadastro_produto);
        fornecedor_produto->setObjectName("fornecedor_produto");
        fornecedor_produto->setGeometry(QRect(80, 190, 650, 55));
        codigo_produto = new QLineEdit(cadastro_produto);
        codigo_produto->setObjectName("codigo_produto");
        codigo_produto->setGeometry(QRect(80, 300, 650, 55));
        qtd_produto = new QLineEdit(cadastro_produto);
        qtd_produto->setObjectName("qtd_produto");
        qtd_produto->setGeometry(QRect(80, 400, 250, 55));
        valor_produto = new QLineEdit(cadastro_produto);
        valor_produto->setObjectName("valor_produto");
        valor_produto->setGeometry(QRect(460, 400, 271, 55));
        cadastrar_produto = new QPushButton(cadastro_produto);
        cadastrar_produto->setObjectName("cadastrar_produto");
        cadastrar_produto->setGeometry(QRect(80, 500, 250, 55));
        cadastrar_produto->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);\n"
"color: rgb(255, 255, 255);"));
        tabWidget_2->addTab(cadastro_produto, QString());
        pesquisa_produtos = new QWidget();
        pesquisa_produtos->setObjectName("pesquisa_produtos");
        p_nome_13 = new QLabel(pesquisa_produtos);
        p_nome_13->setObjectName("p_nome_13");
        p_nome_13->setGeometry(QRect(40, 40, 331, 41));
        p_nome_13->setFont(font2);
        campo_produto_pesquisa = new QLineEdit(pesquisa_produtos);
        campo_produto_pesquisa->setObjectName("campo_produto_pesquisa");
        campo_produto_pesquisa->setGeometry(QRect(370, 40, 650, 55));
        pesquisa_produto = new QPushButton(pesquisa_produtos);
        pesquisa_produto->setObjectName("pesquisa_produto");
        pesquisa_produto->setGeometry(QRect(1030, 40, 150, 55));
        pesquisa_produto->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);\n"
"color: rgb(255, 255, 255);"));
        p_nome_28 = new QLabel(pesquisa_produtos);
        p_nome_28->setObjectName("p_nome_28");
        p_nome_28->setGeometry(QRect(40, 140, 111, 41));
        p_nome_28->setFont(font3);
        p_nome_29 = new QLabel(pesquisa_produtos);
        p_nome_29->setObjectName("p_nome_29");
        p_nome_29->setGeometry(QRect(40, 200, 81, 41));
        p_nome_29->setFont(font2);
        p_nome_30 = new QLabel(pesquisa_produtos);
        p_nome_30->setObjectName("p_nome_30");
        p_nome_30->setGeometry(QRect(40, 250, 151, 41));
        p_nome_30->setFont(font2);
        p_nome_31 = new QLabel(pesquisa_produtos);
        p_nome_31->setObjectName("p_nome_31");
        p_nome_31->setGeometry(QRect(40, 300, 101, 41));
        p_nome_31->setFont(font2);
        p_nome_32 = new QLabel(pesquisa_produtos);
        p_nome_32->setObjectName("p_nome_32");
        p_nome_32->setGeometry(QRect(40, 350, 201, 41));
        p_nome_32->setFont(font2);
        p_nome_33 = new QLabel(pesquisa_produtos);
        p_nome_33->setObjectName("p_nome_33");
        p_nome_33->setGeometry(QRect(40, 400, 71, 41));
        p_nome_33->setFont(font2);
        nova_consulta_produtos = new QPushButton(pesquisa_produtos);
        nova_consulta_produtos->setObjectName("nova_consulta_produtos");
        nova_consulta_produtos->setGeometry(QRect(60, 730, 250, 55));
        nova_consulta_produtos->setStyleSheet(QString::fromUtf8("background-color: rgb(224, 27, 36);\n"
"color: rgb(255, 255, 255);"));
        imprimir_nome_produto = new QLabel(pesquisa_produtos);
        imprimir_nome_produto->setObjectName("imprimir_nome_produto");
        imprimir_nome_produto->setGeometry(QRect(130, 210, 800, 30));
        QFont font5;
        font5.setFamilies({QString::fromUtf8("Droid Sans")});
        font5.setPointSize(13);
        imprimir_nome_produto->setFont(font5);
        imprimir_fornecedor_produto = new QLabel(pesquisa_produtos);
        imprimir_fornecedor_produto->setObjectName("imprimir_fornecedor_produto");
        imprimir_fornecedor_produto->setGeometry(QRect(190, 260, 800, 30));
        imprimir_fornecedor_produto->setFont(font5);
        imprimir_codigo_produto = new QLabel(pesquisa_produtos);
        imprimir_codigo_produto->setObjectName("imprimir_codigo_produto");
        imprimir_codigo_produto->setGeometry(QRect(140, 310, 800, 30));
        imprimir_codigo_produto->setFont(font5);
        imprimir_qtd_produto = new QLabel(pesquisa_produtos);
        imprimir_qtd_produto->setObjectName("imprimir_qtd_produto");
        imprimir_qtd_produto->setGeometry(QRect(250, 350, 800, 30));
        imprimir_qtd_produto->setFont(font5);
        imprimir_valor_produto = new QLabel(pesquisa_produtos);
        imprimir_valor_produto->setObjectName("imprimir_valor_produto");
        imprimir_valor_produto->setGeometry(QRect(120, 400, 800, 30));
        imprimir_valor_produto->setFont(font5);
        tabWidget_2->addTab(pesquisa_produtos, QString());
        menu->addTab(produtos, QString());
        fornecedores = new QWidget();
        fornecedores->setObjectName("fornecedores");
        h1_fornecedores = new QLabel(fornecedores);
        h1_fornecedores->setObjectName("h1_fornecedores");
        h1_fornecedores->setGeometry(QRect(30, 30, 321, 61));
        h1_fornecedores->setFont(font1);
        tabWidget_3 = new QTabWidget(fornecedores);
        tabWidget_3->setObjectName("tabWidget_3");
        tabWidget_3->setGeometry(QRect(30, 110, 1470, 1080));
        cadastro_fornecedores = new QWidget();
        cadastro_fornecedores->setObjectName("cadastro_fornecedores");
        p_nome_14 = new QLabel(cadastro_fornecedores);
        p_nome_14->setObjectName("p_nome_14");
        p_nome_14->setGeometry(QRect(50, 50, 91, 41));
        p_nome_14->setFont(font2);
        nome_fornecedor = new QLineEdit(cadastro_fornecedores);
        nome_fornecedor->setObjectName("nome_fornecedor");
        nome_fornecedor->setGeometry(QRect(50, 90, 750, 55));
        p_nome_15 = new QLabel(cadastro_fornecedores);
        p_nome_15->setObjectName("p_nome_15");
        p_nome_15->setGeometry(QRect(50, 160, 91, 41));
        p_nome_15->setFont(font2);
        email_fornecedor = new QLineEdit(cadastro_fornecedores);
        email_fornecedor->setObjectName("email_fornecedor");
        email_fornecedor->setGeometry(QRect(50, 200, 750, 55));
        p_nome_16 = new QLabel(cadastro_fornecedores);
        p_nome_16->setObjectName("p_nome_16");
        p_nome_16->setGeometry(QRect(50, 270, 121, 41));
        p_nome_16->setFont(font2);
        endereco_fornecedor = new QLineEdit(cadastro_fornecedores);
        endereco_fornecedor->setObjectName("endereco_fornecedor");
        endereco_fornecedor->setGeometry(QRect(50, 310, 750, 55));
        p_nome_17 = new QLabel(cadastro_fornecedores);
        p_nome_17->setObjectName("p_nome_17");
        p_nome_17->setGeometry(QRect(50, 380, 191, 41));
        p_nome_17->setFont(font2);
        complemento_fornecedor = new QLineEdit(cadastro_fornecedores);
        complemento_fornecedor->setObjectName("complemento_fornecedor");
        complemento_fornecedor->setGeometry(QRect(50, 420, 750, 55));
        p_nome_18 = new QLabel(cadastro_fornecedores);
        p_nome_18->setObjectName("p_nome_18");
        p_nome_18->setGeometry(QRect(50, 490, 81, 41));
        p_nome_18->setFont(font2);
        cnpj_fornecedor = new QLineEdit(cadastro_fornecedores);
        cnpj_fornecedor->setObjectName("cnpj_fornecedor");
        cnpj_fornecedor->setGeometry(QRect(50, 530, 350, 55));
        p_nome_19 = new QLabel(cadastro_fornecedores);
        p_nome_19->setObjectName("p_nome_19");
        p_nome_19->setGeometry(QRect(440, 490, 121, 41));
        p_nome_19->setFont(font2);
        telefone_fornecedor = new QLineEdit(cadastro_fornecedores);
        telefone_fornecedor->setObjectName("telefone_fornecedor");
        telefone_fornecedor->setGeometry(QRect(440, 530, 350, 55));
        cadastrar_fornecedor = new QPushButton(cadastro_fornecedores);
        cadastrar_fornecedor->setObjectName("cadastrar_fornecedor");
        cadastrar_fornecedor->setGeometry(QRect(50, 640, 350, 55));
        cadastrar_fornecedor->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);\n"
"color: rgb(255, 255, 255);"));
        tabWidget_3->addTab(cadastro_fornecedores, QString());
        pesquisa_fornecedores = new QWidget();
        pesquisa_fornecedores->setObjectName("pesquisa_fornecedores");
        p_nome_20 = new QLabel(pesquisa_fornecedores);
        p_nome_20->setObjectName("p_nome_20");
        p_nome_20->setGeometry(QRect(60, 50, 491, 41));
        p_nome_20->setFont(font2);
        campo_pesquisa_fornecedor = new QLineEdit(pesquisa_fornecedores);
        campo_pesquisa_fornecedor->setObjectName("campo_pesquisa_fornecedor");
        campo_pesquisa_fornecedor->setGeometry(QRect(560, 40, 500, 55));
        pesquisa_fornecedor = new QPushButton(pesquisa_fornecedores);
        pesquisa_fornecedor->setObjectName("pesquisa_fornecedor");
        pesquisa_fornecedor->setGeometry(QRect(1080, 40, 150, 55));
        pesquisa_fornecedor->setStyleSheet(QString::fromUtf8("background-color: rgb(28, 113, 216);\n"
"color: rgb(255, 255, 255);"));
        p_nome_34 = new QLabel(pesquisa_fornecedores);
        p_nome_34->setObjectName("p_nome_34");
        p_nome_34->setGeometry(QRect(60, 130, 191, 41));
        p_nome_34->setFont(font3);
        p_nome_35 = new QLabel(pesquisa_fornecedores);
        p_nome_35->setObjectName("p_nome_35");
        p_nome_35->setGeometry(QRect(60, 180, 81, 41));
        p_nome_35->setFont(font2);
        p_nome_36 = new QLabel(pesquisa_fornecedores);
        p_nome_36->setObjectName("p_nome_36");
        p_nome_36->setGeometry(QRect(60, 230, 81, 41));
        p_nome_36->setFont(font2);
        p_nome_37 = new QLabel(pesquisa_fornecedores);
        p_nome_37->setObjectName("p_nome_37");
        p_nome_37->setGeometry(QRect(60, 280, 121, 41));
        p_nome_37->setFont(font2);
        p_nome_38 = new QLabel(pesquisa_fornecedores);
        p_nome_38->setObjectName("p_nome_38");
        p_nome_38->setGeometry(QRect(60, 330, 181, 41));
        p_nome_38->setFont(font2);
        p_nome_39 = new QLabel(pesquisa_fornecedores);
        p_nome_39->setObjectName("p_nome_39");
        p_nome_39->setGeometry(QRect(60, 380, 71, 41));
        p_nome_39->setFont(font2);
        p_nome_40 = new QLabel(pesquisa_fornecedores);
        p_nome_40->setObjectName("p_nome_40");
        p_nome_40->setGeometry(QRect(60, 430, 111, 41));
        p_nome_40->setFont(font2);
        imprimir_nome_fornecedor = new QLabel(pesquisa_fornecedores);
        imprimir_nome_fornecedor->setObjectName("imprimir_nome_fornecedor");
        imprimir_nome_fornecedor->setGeometry(QRect(150, 190, 800, 30));
        QFont font6;
        font6.setPointSize(13);
        imprimir_nome_fornecedor->setFont(font6);
        imprimir_email_fornecedor = new QLabel(pesquisa_fornecedores);
        imprimir_email_fornecedor->setObjectName("imprimir_email_fornecedor");
        imprimir_email_fornecedor->setGeometry(QRect(140, 240, 800, 30));
        imprimir_email_fornecedor->setFont(font6);
        imprimir_endereco_fornecedor = new QLabel(pesquisa_fornecedores);
        imprimir_endereco_fornecedor->setObjectName("imprimir_endereco_fornecedor");
        imprimir_endereco_fornecedor->setGeometry(QRect(180, 290, 800, 30));
        imprimir_endereco_fornecedor->setFont(font6);
        imprimir_complemento_fornecedor = new QLabel(pesquisa_fornecedores);
        imprimir_complemento_fornecedor->setObjectName("imprimir_complemento_fornecedor");
        imprimir_complemento_fornecedor->setGeometry(QRect(240, 340, 800, 30));
        imprimir_complemento_fornecedor->setFont(font6);
        imprimir_cnpj_fornecedor = new QLabel(pesquisa_fornecedores);
        imprimir_cnpj_fornecedor->setObjectName("imprimir_cnpj_fornecedor");
        imprimir_cnpj_fornecedor->setGeometry(QRect(130, 390, 800, 30));
        imprimir_cnpj_fornecedor->setFont(font6);
        imprimir_telefone_fornecedor = new QLabel(pesquisa_fornecedores);
        imprimir_telefone_fornecedor->setObjectName("imprimir_telefone_fornecedor");
        imprimir_telefone_fornecedor->setGeometry(QRect(180, 440, 800, 30));
        imprimir_telefone_fornecedor->setFont(font6);
        nova_consulta_fornecedor = new QPushButton(pesquisa_fornecedores);
        nova_consulta_fornecedor->setObjectName("nova_consulta_fornecedor");
        nova_consulta_fornecedor->setGeometry(QRect(60, 750, 250, 55));
        nova_consulta_fornecedor->setStyleSheet(QString::fromUtf8("background-color: rgb(224, 27, 36);\n"
"color: rgb(255, 255, 255);"));
        tabWidget_3->addTab(pesquisa_fornecedores, QString());
        menu->addTab(fornecedores, QString());
        Stockman->setCentralWidget(centralwidget);

        retranslateUi(Stockman);

        menu->setCurrentIndex(3);
        tabWidget->setCurrentIndex(1);
        tabWidget_2->setCurrentIndex(1);
        tabWidget_3->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(Stockman);
    } // setupUi

    void retranslateUi(QMainWindow *Stockman)
    {
        Stockman->setWindowTitle(QCoreApplication::translate("Stockman", "Stockman", nullptr));
        label_menu_fundo->setText(QString());
        logo_menu->setText(QString());
        label_clientes_menu->setText(QCoreApplication::translate("Stockman", "Clientes", nullptr));
        label_produtos_menu->setText(QCoreApplication::translate("Stockman", "Produtos", nullptr));
        label_fornecedores_menu->setText(QCoreApplication::translate("Stockman", "Fornecedores", nullptr));
        icon_clientes->setText(QString());
        icon_produtos->setText(QString());
        icon_fornecedores->setText(QString());
        hero->setText(QString());
        menu->setTabText(menu->indexOf(home), QCoreApplication::translate("Stockman", "Home", nullptr));
        h1_clientes->setText(QCoreApplication::translate("Stockman", "Clientes", nullptr));
        p_nome->setText(QCoreApplication::translate("Stockman", "Nome:", nullptr));
        cliente_nome->setPlaceholderText(QCoreApplication::translate("Stockman", "  Digite o nome do cliente aqui...", nullptr));
        p_nome_2->setText(QCoreApplication::translate("Stockman", "Email:", nullptr));
        cliente_email->setPlaceholderText(QCoreApplication::translate("Stockman", "  exemplo@mail.com", nullptr));
        p_nome_3->setText(QCoreApplication::translate("Stockman", "Endere\303\247o:", nullptr));
        cliente_endereco->setPlaceholderText(QCoreApplication::translate("Stockman", "   Digite o endere\303\247o aqui...", nullptr));
        p_nome_4->setText(QCoreApplication::translate("Stockman", "Complemento:", nullptr));
        cliente_complemento->setPlaceholderText(QCoreApplication::translate("Stockman", "   Digite o complemento aqui...", nullptr));
        p_nome_5->setText(QCoreApplication::translate("Stockman", "CPF:", nullptr));
        cliente_cpf->setPlaceholderText(QCoreApplication::translate("Stockman", "   000.000.000-00", nullptr));
        p_nome_6->setText(QCoreApplication::translate("Stockman", "Telefone:", nullptr));
        cliente_telefone->setPlaceholderText(QCoreApplication::translate("Stockman", "  (XX) 9 XXXX-XXXX", nullptr));
        cadastrar_cliente->setText(QCoreApplication::translate("Stockman", "Cadastrar", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(cadastro_cliente), QCoreApplication::translate("Stockman", "Cadastrar", nullptr));
        p_nome_7->setText(QCoreApplication::translate("Stockman", "Digite o n\303\272mero do CPF do cliente:", nullptr));
        campo_cliente_pesquisa->setPlaceholderText(QCoreApplication::translate("Stockman", "  Exemplo: 123.456.789.10", nullptr));
        pesquisa_cliente_2->setText(QCoreApplication::translate("Stockman", "Pesquisar", nullptr));
        p_nome_21->setText(QCoreApplication::translate("Stockman", "Cliente", nullptr));
        p_nome_22->setText(QCoreApplication::translate("Stockman", "Nome:", nullptr));
        p_nome_23->setText(QCoreApplication::translate("Stockman", "Email:", nullptr));
        p_nome_24->setText(QCoreApplication::translate("Stockman", "Endere\303\247o:", nullptr));
        p_nome_25->setText(QCoreApplication::translate("Stockman", "Complemento:", nullptr));
        p_nome_26->setText(QCoreApplication::translate("Stockman", "CPF:", nullptr));
        p_nome_27->setText(QCoreApplication::translate("Stockman", "Telefone:", nullptr));
        imprimir_nome_cliente->setText(QString());
        imprimir_email_cliente->setText(QString());
        imprimir_endereco_cliente->setText(QString());
        imprimir_complemento_cliente->setText(QString());
        imprimir_cpf_cliente->setText(QString());
        imprimir_telefone_cliente->setText(QString());
        pushButton->setText(QCoreApplication::translate("Stockman", "Nova consulta", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(pesquisa_cliente), QCoreApplication::translate("Stockman", "Pesquisar", nullptr));
        menu->setTabText(menu->indexOf(clientes), QCoreApplication::translate("Stockman", "Clientes", nullptr));
        h1_produtos->setText(QCoreApplication::translate("Stockman", "Produtos", nullptr));
        p_nome_8->setText(QCoreApplication::translate("Stockman", "Nome:", nullptr));
        p_nome_9->setText(QCoreApplication::translate("Stockman", "Fornecedor:", nullptr));
        p_nome_10->setText(QCoreApplication::translate("Stockman", "C\303\263digo:", nullptr));
        p_nome_11->setText(QCoreApplication::translate("Stockman", "Qtd. no Estoque:", nullptr));
        p_nome_12->setText(QCoreApplication::translate("Stockman", "Valor:", nullptr));
        nome_produto->setPlaceholderText(QCoreApplication::translate("Stockman", "  Digite o nome do produto aqui...", nullptr));
        fornecedor_produto->setPlaceholderText(QCoreApplication::translate("Stockman", "  Digite o nome da empresa aqui...", nullptr));
        codigo_produto->setPlaceholderText(QCoreApplication::translate("Stockman", "   XXXX", nullptr));
        qtd_produto->setPlaceholderText(QCoreApplication::translate("Stockman", "                                         unidades", nullptr));
        valor_produto->setPlaceholderText(QCoreApplication::translate("Stockman", "   R$", nullptr));
        cadastrar_produto->setText(QCoreApplication::translate("Stockman", "Cadastrar", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(cadastro_produto), QCoreApplication::translate("Stockman", "Cadastrar", nullptr));
        p_nome_13->setText(QCoreApplication::translate("Stockman", "Digite o nome do produto:", nullptr));
        campo_produto_pesquisa->setPlaceholderText(QCoreApplication::translate("Stockman", "   Exemplo: Boneco do Gabigol", nullptr));
        pesquisa_produto->setText(QCoreApplication::translate("Stockman", "Pesquisar", nullptr));
        p_nome_28->setText(QCoreApplication::translate("Stockman", "Produto:", nullptr));
        p_nome_29->setText(QCoreApplication::translate("Stockman", "Nome:", nullptr));
        p_nome_30->setText(QCoreApplication::translate("Stockman", "Fornecedor:", nullptr));
        p_nome_31->setText(QCoreApplication::translate("Stockman", "C\303\263digo:", nullptr));
        p_nome_32->setText(QCoreApplication::translate("Stockman", "Qtd. no Estoque:", nullptr));
        p_nome_33->setText(QCoreApplication::translate("Stockman", "Valor:", nullptr));
        nova_consulta_produtos->setText(QCoreApplication::translate("Stockman", "Nova Consulta", nullptr));
        imprimir_nome_produto->setText(QString());
        imprimir_fornecedor_produto->setText(QString());
        imprimir_codigo_produto->setText(QString());
        imprimir_qtd_produto->setText(QString());
        imprimir_valor_produto->setText(QString());
        tabWidget_2->setTabText(tabWidget_2->indexOf(pesquisa_produtos), QCoreApplication::translate("Stockman", "Pesquisar", nullptr));
        menu->setTabText(menu->indexOf(produtos), QCoreApplication::translate("Stockman", "Produtos", nullptr));
        h1_fornecedores->setText(QCoreApplication::translate("Stockman", "Fornecedores", nullptr));
        p_nome_14->setText(QCoreApplication::translate("Stockman", "Nome:", nullptr));
        nome_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "  Digite o nome do fornecedor aqui..", nullptr));
        p_nome_15->setText(QCoreApplication::translate("Stockman", "Email:", nullptr));
        email_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "  email@mail.com", nullptr));
        p_nome_16->setText(QCoreApplication::translate("Stockman", "Endere\303\247o:", nullptr));
        endereco_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "  Digite o endere\303\247o aqui..", nullptr));
        p_nome_17->setText(QCoreApplication::translate("Stockman", "Complemento:", nullptr));
        complemento_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "  Digite o complemento aqui..", nullptr));
        p_nome_18->setText(QCoreApplication::translate("Stockman", "CNPJ:", nullptr));
        cnpj_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "  71.341.585/0001-51", nullptr));
        p_nome_19->setText(QCoreApplication::translate("Stockman", "Telefone:", nullptr));
        telefone_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "   (XX) 9 XXXX-XXXX", nullptr));
        cadastrar_fornecedor->setText(QCoreApplication::translate("Stockman", "Cadastrar", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(cadastro_fornecedores), QCoreApplication::translate("Stockman", "Cadastrar", nullptr));
        p_nome_20->setText(QCoreApplication::translate("Stockman", "Digite o n\303\272mero do CNPJ do fornecedor:", nullptr));
        campo_pesquisa_fornecedor->setText(QString());
        campo_pesquisa_fornecedor->setPlaceholderText(QCoreApplication::translate("Stockman", "  Exemplo: 57090447000116", nullptr));
        pesquisa_fornecedor->setText(QCoreApplication::translate("Stockman", "Pesquisar", nullptr));
        p_nome_34->setText(QCoreApplication::translate("Stockman", "Fornecedor", nullptr));
        p_nome_35->setText(QCoreApplication::translate("Stockman", "Nome: ", nullptr));
        p_nome_36->setText(QCoreApplication::translate("Stockman", "Email:", nullptr));
        p_nome_37->setText(QCoreApplication::translate("Stockman", "Endere\303\247o:", nullptr));
        p_nome_38->setText(QCoreApplication::translate("Stockman", "Complemento:", nullptr));
        p_nome_39->setText(QCoreApplication::translate("Stockman", "CNPJ:", nullptr));
        p_nome_40->setText(QCoreApplication::translate("Stockman", "Telefone:", nullptr));
        imprimir_nome_fornecedor->setText(QString());
        imprimir_email_fornecedor->setText(QString());
        imprimir_endereco_fornecedor->setText(QString());
        imprimir_complemento_fornecedor->setText(QString());
        imprimir_cnpj_fornecedor->setText(QString());
        imprimir_telefone_fornecedor->setText(QString());
        nova_consulta_fornecedor->setText(QCoreApplication::translate("Stockman", "Nova Consulta", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(pesquisa_fornecedores), QCoreApplication::translate("Stockman", "Pesquisar", nullptr));
        menu->setTabText(menu->indexOf(fornecedores), QCoreApplication::translate("Stockman", "Fornecedores", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Stockman: public Ui_Stockman {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_STOCKMAN_H
